version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/cuckoofilter

    steps:
      - checkout

      - restore_cache:
          keys:
            - cuckoofilter-{{ checksum "pom.xml" }}
            - cuckoofilter-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: cuckoofilter-{{ checksum "pom.xml" }}

      - run: mvn test